services:
  app:
    build:
      context: .
      args:
        - VITE_FIREBASE_API_KEY
        - VITE_FIREBASE_AUTH_DOMAIN
        - VITE_FIREBASE_DATABASE_URL
        - VITE_FIREBASE_PROJECT_ID
        - VITE_FIREBASE_STORAGE_BUCKET
        - VITE_FIREBASE_MESSAGING_SENDER_ID
        - VITE_FIREBASE_APP_ID
    container_name: track_acdc_app
    restart: always
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
